Tech-416- how to create a validator node
chain4travel/camino-docs pull request #40
Opened 2022-11-18 14:14 UTC by mo-c4t

- note for the version compatible with testnet is v0.2.1-rc2
- Setup camino node manually: replace github ssh url to https url
- Setup camino node manually: adding a hint about public-ip option
- steps to add a validator node
- setup camino node from install script: note to add network-id option in the config file when running on testnet
- replacing "an Camino node" to "a Camino node"?
- adding Ubuntu 22.04 to the supported OS

2022-11-18 15:09 UTC, c4t-ag requested changes
This will help! Thx much!
In the initial article there is often person switching between neutral / you / their ....
I suggest that some native nglish speaker jumps in here

2022-11-21 12:14 UTC, mo-c4t commented
> This will help! Thx much! In the initial article there is often person switching between neutral / you / their .... I suggest that some native nglish speaker jumps in here

Do you mean this sentence 
"Validators must know their public facing IP addresses so they can let other nodes know how to connect to them. So If your node will run as a validator, you need to use `--public-ip` option. For more info check [public-ip flag](camino-node-config-flags.md#public-ip)"

or are you talking about the whole documentation ?

Who can help with this ?

2022-11-23 10:48 UTC, tabeaarnold commented on docs/apps/nodes/set-up-node-with-installer.md
> +If you previously ran a Camino-Node node on this computer, you will have local node files stored in `$HOME/.caminogo` directory. Those files will not be disturbed, and node set up by the script will
If you previously ran a Camino-Node node on this computer, you will have _the_ local node files stored in `$HOME/.caminogo` directory. Those files will not be disturbed and _the_ node set up by the script will continue _its_ operation with the same identity and state it had before. That being said, for your node's security, back up `staker.crt` and `staker.key` files, found in `$HOME/.caminogo/staking` and store them somewhere secure. You can use those files to recreate your node on a different computer if you ever need to.

2022-11-23 10:48 UTC, tabeaarnold commented on docs/apps/nodes/set-up-node-with-docker.md
> +That's it, you're running a Camino-Node node on docker! Congratulations! Let us know you did it on our [Twitter](https://twitter.com/CaminoFndtn) or [Discord](https://discord.gg/K5THjAweFB)!
Share it on our

2022-11-23 10:48 UTC, tabeaarnold commented on docs/apps/nodes/run-camino-node.md
> +Validators must know their public facing IP addresses so they can let other nodes know how to connect to them. So If your node will run as a validator, you need to use `--public-ip` option. For more
... you need to use the ....

2022-11-23 10:48 UTC, tabeaarnold commented on docs/apps/nodes/run-camino-node.md
> +Let’s install Camino-Node, the Go implementation of a Camino node, and connect to the Camino Public Testnet (Columbus).
Let's install the Camino-Node

2022-11-23 17:17 UTC, c4t-ag approved these changes

2022-11-24 08:24 UTC, merged